export const containerWrapper: string;
export const container: string;
export const header: string;
export const title: string;
export const origTitle: string;
export const year: string;
export const description: string;
export const tagline: string;
export const genresList: string;
